### PR TITLE
Relicence project under MIT.

### PR DESCRIPTION
**Pull request by awnumar**

### CODE REVIEW

**Comment by tobbbles** [comment]
This isn't a major software release. Version numbers

**Comment by awnumar** [comment]
One of them has to change for the relicencing, otherwise we can't push the relicenced version to PyPi. I would have thought a major update would be cleaner, i.e. from 6.0.0 onwards it's MIT.

**Comment by tobbbles** [comment]
Do you have a feature you want to implement which we can bundle this in with?

**Comment by awnumar** [comment]
Not that I can think of. You can suggest a change or improvement and I can maybe implement that.

**Pull request merged**
