### PR TITLE
Add fingerprints and improve security.

### PR DESCRIPTION
**Pull request by awnumar**
Pull request to remove master password confirmation and generally increase security by upping default parameters and changing the way we calculate the readable passwords.

This will break reverse compatibility.

Resolves #25.

### CODE REVIEW

**Comment by tobbbles** [comment]
Is this ready to merge and working/tested?

**Comment by awnumar** [comment]
Not yet. I'm still thinking about whether to break reverse compatibility or
not.
- I'll probably reorganize the code with this PR.

**Comment by awnumar** [comment]
Todo: Enable mac-address as keyword in generating fingerprints.

**Comment by awnumar** [comment]
Actually, after reconsidering, I don't believe adding mac-addresses is feasable. @mnzt merge?

**Comment by tobbbles** [comment]
Feel like writing a test?

**Comment by awnumar** [comment]
Feel free to open a PR, mate.

**Comment by tobbbles** [comment]
:accept:

**Pull request merged**
